Fixes geographical areas and workflow
Fix for JavaScript error ReferenceError: isGroup is not defined:
https://trello.com/c/yxzF0sA0/619-editing-geographical-areas-is-broken-referenceerror-isgroup-is-not-defined

Fix for missing conformance error method

ME113 undefined local variable or method 'additional_code_type' for MeasureValidator:Class

Workflow for geographical areas