Default instance index to 0 in non-CF environments
With a clean clone, after running bin/setup, the "foreman start"
command fails because the Procfile runs DB migrate on the 'first instance'
before starting the webserver. Locally VCAP_APPLICATION doesn't tend
to be set, so the task fails with:

NoMethodError: undefined method `zero?' for nil:NilClass