[ROLLBACKS] updated to work with workbaskets
Previously we got the issue reported by sentry:

```
undefined method `manual_add=' for #<Workbaskets::Workbasket:0x00007f95ae9b5ac8>
```

This PR fixes that.

[SENTRY ISSUE](https://sentry.io/bit-zesty-client-apps/management/issues/648363976/?referrer=slack)
[TRELLO CARD](https://trello.com/c/gKHXVPgX/412-dit-rollbacks-functionality-issue-nomethoderror-undefined-method-manualadd-for-workbasket)